from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import Task

MICRO_PREFIX = "[MICRO]"


def _is_micro(task: Task) -> bool:
    return (task.title or "").strip().startswith(MICRO_PREFIX)


def _micro_title(kind: str, parent_title: str) -> str:
    # kind: "Starter" or "DoD push"
    return f"{MICRO_PREFIX} {kind} for: {parent_title}"


def _micro_exists(db: Session, parent_task_id: int, title: str) -> bool:
    existing = db.scalars(
        select(Task.id).where(
            Task.parent_task_id == parent_task_id,
            Task.title == title,
            Task.completed == False,  # noqa: E712
        )
    ).first()
    return existing is not None


async def generate_microtasks(db: Session, task: Task, llm_client) -> None:
    """
    Generates microtasks ONLY for real tasks, never for microtasks.
    Also avoids duplicates and only creates what is missing.
    """

    # 1) Hard stop: do not generate microtasks for microtasks
    if _is_micro(task):
        return

    parent_title = task.title

    # 2) Starter microtask only if missing
    if not (task.starter and task.starter.strip()):
        title = _micro_title("Starter", parent_title)
        if not _micro_exists(db, task.id, title):
            db.add(
                Task(
                    goal_id=task.goal_id,
                    project=task.project,
                    title=title,
                    notes="Fill Starter (2 min) for parent task.\n(Autogenerated microtask.)",
                    estimated_minutes=10,
                    priority=task.priority,
                    due_date=task.due_date,
                    blocks_me=True,
                    parent_task_id=task.id,
                )
            )

    # 3) DoD microtask only if missing
    if not (task.dod and task.dod.strip()):
        title = _micro_title("DoD push", parent_title)
        if not _micro_exists(db, task.id, title):
            db.add(
                Task(
                    goal_id=task.goal_id,
                    project=task.project,
                    title=title,
                    notes="Fill DoD (measurable outcome) for parent task.\n(Autogenerated microtask.)",
                    estimated_minutes=20,
                    priority=task.priority,
                    due_date=task.due_date,
                    blocks_me=True,
                    parent_task_id=task.id,
                )
            )

    db.commit()
